class_name Loc
extends Node

const STRINGS := {
	"zh": {
		"task_title":   "任務",
		"fall_msg":     "FALL DOWN!\nR: 重置   Z: 復原   ESC: 選關",
		"victory_sub":  "Level %s  ·  %d 步",
		"diverge_btn":  "[V] 分裂",
		"merge_btn":    "[V] 合併",
		"fetch_btn":    "[F] FETCH MERGE",
		"preview_on":   "[M] 取消預覽",
		"preview_off":  "[M] 預覽",
		"footer_esc":   "[ESC] 選擇關卡",
		"footer_f1":    "[F1] 說明",
		"footer_r":     "[R] 重置",
		"footer_z":     "[Z] 退回",
		"tab_left":     "< [TAB]",
		"tab_right":    "[TAB] >",
		"spotlight_next":   "按任意鍵繼續",
		"spotlight_last":   "按任意鍵開始",
		"desc_close":   "按任意鍵關閉",
		"ls_zone":      "Zone %d",
		"ls_done":      "Done",
		"ls_no_levels": "No levels found",
		"ls_footer1":   "  W/S: select level    ",
		"ls_footer2":   "  A/D: zone   Enter/Space: start   Esc: 設定",
		"mutex_ann1":   "藍色 = 可合併",
		"mutex_ann2":   "灰色 = 無法合併",
		"spot_player_title": "角色",
		"spot_player_l1":    "藍色圓圈是你控制的角色",
		"spot_player_l2":    "白色箭頭代表角色面向方向",
		"spot_player_l3":    "使用 W/A/S/D 或方向鍵移動",
		"spot_goal_title":   "終點",
		"spot_goal_l1":      "黃色圓圈是終點",
		"spot_goal_l2":      "走到閃爍的終點即可過關",
		"spot_core1_title":  "核心",
		"spot_core1_l1":     "菱形色塊，可被推動",
		"spot_core2_title":  "核心",
		"spot_core2_l1":     "面對核心移動可推動一格",
		"spot_core2_l2":     "一次只能推動一個核心",
		"spot_switch_title": "目標",
		"spot_switch_l1":    "灰色菱形框，啟動點",
		"spot_switch_l2":    "將核心推進目標格可啟動",
		"spot_switch_l3":    "所有目標啟動後，終點將開啟",
		"spot_divpt_title":  "分裂點",
		"spot_divpt_l1":     "綠色圓點是分裂點",
		"spot_divpt_l2":     "取得分裂點增加可分裂次數",
		"spot_divpt_l3":     "合併狀態才能取得分裂點",
		"spot_hole_title":   "空洞",
		"spot_hole_l1":      "紅色的空洞格，無法通過",
		"spot_hole_l2":      "推動核心進空洞可修復為道路",
		"spot_diverge_title": "分裂空間",
		"spot_diverge_l1":    "當前狀態複製成兩個空間",
		"spot_diverge_l2":    "一次可控制一個空間的角色",
		"spot_diverge_l3":    "目前控制對象會在中央大圖",
		"spot_shadow_title":  "殘影",
		"spot_shadow_l1":     "虛線菱形",
		"spot_shadow_l2":     "不可推動也不可穿透",
		"spot_turn_title":    "轉向",
		"spot_turn_l1":       "若核心在側面，朝核心按方向鍵",
		"spot_turn_l2":       "會原地轉向正對核心",
		"spot_filled_title":  "修復",
		"spot_filled_l1":     "消耗核心修復空洞",
		"spot_filled_l2":     "修復後會保留核心顏色",
		"spot_preview_title": "預覽模式",
		"spot_preview_l1":    "兩空間疊合，另一空間的角色變灰，核心呈現縮小半透明",
		"spot_preview_l2":    "可以繼續操作，按 [Tab] 可即時切換角色",
		"spot_preview_l3":    "再按 [V] 合併或 [M] 退出預覽",
		"spot_hl_div_ann1":   "綠色 = 可分裂",
		"spot_hl_div_ann2":   "灰色 = 無法分裂",
	},
	"en": {
		"task_title":   "Mission",
		"fall_msg":     "FALL DOWN!\nR: restart   Z: undo   ESC: level select",
		"victory_sub":  "Level %s  ·  %d steps",
		"diverge_btn":  "[V] Diverge",
		"merge_btn":    "[V] Merge",
		"fetch_btn":    "[F] Fetch Merge",
		"preview_on":   "[M] Cancel Preview",
		"preview_off":  "[M] Preview",
		"footer_esc":   "[ESC] Level Select",
		"footer_f1":    "[F1] Info",
		"footer_r":     "[R] Restart",
		"footer_z":     "[Z] Undo",
		"tab_left":     "< [TAB]",
		"tab_right":    "[TAB] >",
		"spotlight_next":   "Press any key to continue",
		"spotlight_last":   "Press any key to start",
		"desc_close":   "Press any key to close",
		"ls_zone":      "Zone %d",
		"ls_done":      "Done",
		"ls_no_levels": "No levels found",
		"ls_footer1":   "  W/S: select level    ",
		"ls_footer2":   "  A/D: zone   Enter/Space: start   Esc: settings",
		"mutex_ann1":   "Blue = can merge",
		"mutex_ann2":   "Gray = cannot merge",
		"spot_player_title": "Player",
		"spot_player_l1":    "The blue circle is your character",
		"spot_player_l2":    "The white arrow shows the facing direction",
		"spot_player_l3":    "Move with W/A/S/D or arrow keys",
		"spot_goal_title":   "Goal",
		"spot_goal_l1":      "The yellow circle is the goal",
		"spot_goal_l2":      "Step onto the flashing goal to clear the level",
		"spot_core1_title":  "Core",
		"spot_core1_l1":     "A diamond block that can be pushed",
		"spot_core2_title":  "Core",
		"spot_core2_l1":     "Move toward the core to push it one step",
		"spot_core2_l2":     "You can only push one core at a time",
		"spot_switch_title": "Target",
		"spot_switch_l1":    "Gray diamond frame — an activation point",
		"spot_switch_l2":    "Push a core onto a target to activate it",
		"spot_switch_l3":    "The goal opens when all targets are activated",
		"spot_divpt_title":  "Diverge Point",
		"spot_divpt_l1":     "Green dots are diverge points",
		"spot_divpt_l2":     "Collecting one increases your diverge count",
		"spot_divpt_l3":     "You can only collect them while merged",
		"spot_hole_title":   "Void",
		"spot_hole_l1":      "Red Void tiles cannot be crossed",
		"spot_hole_l2":      "Push a Core into a Void to repair it as a path",
		"spot_diverge_title": "Diverged Space",
		"spot_diverge_l1":    "The current state is copied into two spaces",
		"spot_diverge_l2":    "You control one space's player at a time",
		"spot_diverge_l3":    "The active space is shown in the large center panel",
		"spot_shadow_title":  "Trace",
		"spot_shadow_l1":     "Dashed diamond",
		"spot_shadow_l2":     "Cannot be pushed or passed through",
		"spot_turn_title":    "Turn",
		"spot_turn_l1":       "If a core is to your side, press toward it",
		"spot_turn_l2":       "You'll turn to face it in place",
		"spot_filled_title":  "Repaired",
		"spot_filled_l1":     "The Core is consumed to repair the Void",
		"spot_filled_l2":     "The repaired Void keeps the Core's color",
		"spot_preview_title": "Preview Mode",
		"spot_preview_l1":    "Spaces overlap; the other player turns gray, cores become small and translucent",
		"spot_preview_l2":    "You can still move; press [Tab] to switch players instantly",
		"spot_preview_l3":    "Press [V] to merge or [M] to exit preview",
		"spot_hl_div_ann1":   "Green = can diverge",
		"spot_hl_div_ann2":   "Gray = cannot diverge",
	},
}


## Look up a localized string. Safe to call from any context including _draw().
static func t(key: String) -> String:
	var lang := "zh"
	var ml := Engine.get_main_loop()
	if ml is SceneTree:
		var gd = (ml as SceneTree).root.get_node_or_null("GameData")
		if gd != null:
			var l = gd.get("language")
			if l != null:
				lang = str(l)
	var table: Dictionary = STRINGS.get(lang, STRINGS["zh"]) as Dictionary
	return str(table.get(key, STRINGS["zh"].get(key, key)))
